name: gradle-build
description: executes gradle build and uploads build artifacts
inputs:
  working-directory:
    required: true
    description: directory of gradle sources
  upload-artifacts:
    required: false
    description: upload build artifacts
    default: true
  skip-tests:
    required: false
    description: skip tests
    default: false
  github-token:
    required: false
    description: github token
  sonar-token:
    required: false
    description: sonar token

runs:
  using: "composite"
  steps:
    - name: setup java
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: ${{ env.JAVA_DIST }}
        cache: gradle
    - name: setup docker buildx
      uses: docker/setup-buildx-action@v3
    - name: gradle build
      working-directory: ${{ inputs.working-directory }}
      run: |-
        if [[ ${{ inputs.skip-tests }} == true ]]; then
          ./gradlew build -x test
        else
          ./gradlew build
        fi
      shell: bash
    - name: sonarcloud scan backend
      uses: SonarSource/sonarcloud-github-action@v2.1.1
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        SONAR_TOKEN: ${{ inputs.sonar-token }}
      with:
        projectBaseDir: ${{ inputs.working-directory }}
    - name: upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.working-directory }}
        # action ignores default working directory
        # see https://github.com/actions/upload-artifact/issues/294
        path: ${{ inputs.working-directory }}/build/libs
        retention-days: 1
        if-no-files-found: error
      if: ${{ inputs.upload-artifacts }}
