version: 2
updates:
  - package-ecosystem: "npm"
    directory: "frontend"
    schedule:
      interval: "daily"
    assignees:
      - "leoantferrari"
    labels:
      - "dependencies"
      - "frontend"

  - package-ecosystem: "gradle"
    directory: "backend"
    schedule:
      interval: "daily"
    assignees:
      - "larawaespe"
    labels:
      - "dependencies"
      - "backend"

  - package-ecosystem: "npm"
    directory: "printer/printer-server"
    schedule:
      interval: "daily"
    assignees:
      - "mcluky"
    labels:
      - "dependencies"
      - "printer-server"

  - package-ecosystem: "npm"
    directory: "printer/printer-api-lib"
    schedule:
      interval: "daily"
    assignees:
      - "mcluky"
    labels:
      - "dependencies"
      - "printer-api-lib"