version: '3.1'

services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: micha
      MYSQL_DATABASE: micha
      MYSQL_USER: micha
      MYSQL_PASSWORD: micha
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
volumes:
  db_data:
