version: '3.1'

services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: micha
      MYSQL_DATABASE: micha
      MYSQL_USER: micha
      MYSQL_PASSWORD: micha
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  app:
    platform: linux/x86_64
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/micha
      SPRING_DATASOURCE_USERNAME: micha
      SPRING_DATASOURCE_PASSWORD: micha
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_SQL_INIT_MODE: always
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: stage
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: always

volumes:
  db_data:
