version: '3.1'

services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: simonsays
      MYSQL_DATABASE: simonsays
      MYSQL_USER: simonsays
      MYSQL_PASSWORD: simonsays
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
volumes:
  db_data:
