version: '3.1'

services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: $dbRootPassword
      MYSQL_DATABASE: $dbName
      MYSQL_USER: $dbUser
      MYSQL_PASSWORD: $dbPassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  app:
    platform: linux/x86_64
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/$dbName
      SPRING_DATASOURCE_USERNAME: $dbUser
      SPRING_DATASOURCE_PASSWORD: $dbPassword
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_SQL_INIT_MODE: always
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: stage
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: always

volumes:
  db_data:
