version: '3.2'
services:
  db:
    image: mysql:8.0
    container_name: simonsays-db
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: simonsays
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: simonsays
      MYSQL_PASSWORD: password
    volumes:
      - db:/var/lib/mysql
volumes:
  dbdata:
  db:
    driver: local