apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.service.name }}
  labels:
    app: {{ .Values.backend.service.name }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.deployment.port }}
      protocol: TCP
  selector:
    app: {{ .Values.backend.deployment.name }}
