apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.service.name }}
  labels:
    app: {{ .Values.frontend.service.name }}
spec:
  type: {{ .Values.backend.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.deployment.port }}
      protocol: TCP
  selector:
    app: {{ .Values.frontend.deployment.name }}
