# Ensure docker compose is installed on your machine
# Run `docker-compose up -d` to start the printer server

version: '3.8'

services:
  printer-server:
    image: ghcr.io/simonsays-pm4/simon-says/printer-server:latest
    network_mode: host
    environment:
      PRINTER_SERVER_ID: "eb6c2108-82c2-4260-93b7-6a0937cf73ef"
      PRINTER_QUEUE_SERVER_BASE_URL: "http://192.168.1.172:8080"
      DRY_RUN: "false"
      DRY_RUN_PRINTER_MAC_ADDRESS: "00:00:00:00:00:01"
    restart: always
    read_only: true
    security_opt:
      - no-new-privileges:true