# database settings
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://simonsays-mysql.simonsays-stage.svc.cluster.local:3306/simonsays
    username: simon
    password: pREEW0Gr6833gbyD
    driver-class-name: com.mysql.cj.jdbc.Driver

debug: on
application:
  url: "https://simonsays-stage.pm4.init-lab.ch/"

# The printer-queue-server application configuration
printer-queue-server:
  # List of frontend origins allowed to communicate with the printer server
  frontend-origins:
    # TODO: Add the URL of your deployed frontend here
    - https://simonsays-stage.pm4.init-lab.ch
