spring:
  datasource:
    url: jdbc:mysql://localhost:3306/simonsays
    username: simon
    password: simonsays
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
debug: on
application:
  url: ""
# Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus