spring:
  datasource:
    url: jdbc:mysql://localhost:3306/$dbName
    username: $dbUser
    password: $dbPassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
