# database settings
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
  datasource:
    url: jdbc:mysql://localhost:3306/simonsays
    username: simonsays
    password: simonsays
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
debug: on
application:
  url: "http://localhost:3000"
