spring:
  datasource:
    url: jdbc:mysql://localhost:3306/simonsays
    username: simonsays
    password: simonsays
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
debug: on
application:
  url: "http://localhost:3000"