# database settings
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/micha
    username: micha
    password: micha
    driver-class-name: com.mysql.cj.jdbc.Driver

