# database settings
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/simonsays
    username: simon
    password: simonsays
    driver-class-name: com.mysql.cj.jdbc.Driver

debug: on
