# database settings
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/simonsays
    username: simonsays
    password: simonsays
    driver-class-name: com.mysql.cj.jdbc.Driver
debug: on
application:
  url: "http://localhost:3000"
  adminToken: "mysecretpassword"

# The printer-queue-server application configuration
printer-queue-server:
  # List of frontend origins allowed to communicate with the printer server
  frontend-origins:
    # TODO: Add the URL of your deployed frontend here
    - https://simonsays-stage.pm4.init-lab.ch
  dry-run: true
  # Will automatically create the printer server on startup and add the respective printer will be assigned
  printer-server-id: "a35e6a08-35ef-42c1-9a09-39d32fc2a5d6"
  takeaway-printer-queue-id: "ef084926-d2be-4a03-9538-c8dd44f19e04"
  takeaway-printer-mac: "50:57:9c:d2:12:53"
  receipt-printer-queue-id: "6f7c2fa6-9401-457e-8a86-618e810b103a"
  receipt-printer-mac: "50:57:9c:d2:12:53"
  # The following settings are optional and can be used to customize the receipt that is printed
  receipt-max-characters-per-line: 49
  receipt-base64-png-logo: "iVBORw0KGgoAAAANSUhEUgAAADwAAAA8CAMAAAANIilAAAAAAXNSR0IArs4c6QAAAEtQTFRFR3BMADaQADWPADWP4AAqADWP5AAodyJl5AAoADaRADyZADWPBDaQADaQADaQ4QAp7gAe4wAo4wAo4AAq4AAq3QAr4QApADeR5AAp7JnuvwAAABd0Uk5TALg4Ujma7QP8"
  receipt-qr-code-content: "https://cevi.net"
  receipt-header: "TEST! Willkommen beim Cevi Burger Festival!"
  receipt-footer: "https://cevi.net"