# database settings
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/simonsays
    username: simon
    password: simonsays
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
debug: on
application:
  url: ""

# The printer-queue-server application configuration
printer-queue-server:
  # List of frontend origins allowed to communicate with the printer server
  frontend-origins:
    # TODO: Add the URL of your deployed frontend here
    - https://simon-says.ch