# database settings
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://simonsays-mysql.simonsays-stage.svc.cluster.local:3306/simonsays
    username: simon
    password: pREEW0Gr6833gbyD
    driver-class-name: com.mysql.cj.jdbc.Driver

debug: on
