backend:
  config:
    adminSecretName: "simonsays-admin"
  deployment:
    name: simonsays-backend
    replicas: 1
    forceRedeploy: false
    image:
      repository: "ghcr.io/simonsays-pm4/simon-says/backend"
      pullSecret: "ghcrio"
      pullPolicy: "IfNotPresent"
    resources:
      requests:
        memory: "250Mi"
        cpu: "200m"
      limits:
        memory: "1Gi"
        cpu: "500m"
    port: 8080
  service:
    name: simonsays-backend
    targetPort: 8080
    port: 8080
  #config:
  #  applicationConfig:
  #    logging:
  #      level:
  #        root: INFO
  ingress:
    host: simonsays-backend-prod.pm4.init-lab.ch
    ingressClassName: "traefik"
    path: /
    pathType: "Prefix"
  probes:
    startup:
      path: /actuator/health/liveness
      options:
        failureThreshold: 18
        periodSeconds: 10
    liveness:
      path: /actuator/health/liveness
      options:
        timeoutSeconds: 3
    readiness:
      path: /actuator/health/readiness
      options:
        timeoutSeconds: 3
frontend:
  deployment:
    name: simonsays-frontend
    replicas: 1
    forceRedeploy: false
    image:
      repository: "ghcr.io/simonsays-pm4/simon-says/frontend"
      pullSecret: "ghcrio"
      pullPolicy: "IfNotPresent"
    resources:
      requests:
        memory: "250Mi"
        cpu: "200m"
      limits:
        memory: "1Gi"
        cpu: "500m"
    port: 8080
  service:
    name: simonsays-frontend
    targetPort: 8080
    port: 8080
  ingress:
    host: simonsays.pm4.init-lab.ch
    ingressClassName: "traefik"
    path: /
    pathType: "Prefix"
mysql:
  auth:
    username: "simon"
    database: "simonsays"