name: backend running on pull requests

on:
  - pull_request
env:
  # GENERAL
  BACKEND_DIRECTORY: backend
  # JAVA env
  JAVA_VERSION: 17
  JAVA_DIST: corretto
jobs:
  kotlin-static-code-analysis:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout sources
        uses: actions/checkout@v4
      #- name: gradle-build
      #  uses: ./.github/actions/gradle-build
      #  with:
      #    working-directory: ${{ env.BACKEND_DIRECTORY }}
      - name: detekt-kotlin-static-code-analysis
        uses: alaegin/Detekt-Action@v1.23.5
        with:
          github_token: ${{ secrets.github_token }}
          detekt_config: backend/config/detekt/detekt.yml
