name: backend manual stage deploy

on:
  workflow_dispatch
env:
  # GENERAL
  BACKEND_DIRECTORY: backend
  # JAVA env
  JAVA_VERSION: 17
  JAVA_DIST: corretto
  # DOCKER env
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/backend
  # HELM env
  HELM_DIRECTORY: helm
  HELM_RELEASE_NAME: simonsays
  # K8S env
  K8S_API: https://pm4.init-lab.ch/k8s/clusters/local
  K8S_NAMESPACE: simonsays-stage


jobs:
  deploy-helm-ci:
    runs-on: ubuntu-22.04
    environment: staging
    steps:
      - name: checkout sources
        uses: actions/checkout@v4
      - name: deploy
        uses: ./.github/actions/helm-release
        with:
          helm-directory: ${{ env.HELM_DIRECTORY }}
          k8s-token: ${{ secrets.K8S_TOKEN }}
          k8s-api: ${{ env.K8S_API }}
          k8s-namespace: ${{ env.K8S_NAMESPACE }}
          helm-release-name: ${{ env.HELM_RELEASE_NAME }}
          helm-values-file: values-stage.yaml
          mysql-root-password: ${{ secrets.MYSQL_ROOT_PASSWORD_STAGING }}
          mysql-password: ${{ secrets.MYSQL_PASSWORD_STAGING }}