name: backend running on each commit

on:
  - push
  - pull_request
env:
  # GENERAL
  BACKEND_DIRECTORY: backend
  # JAVA env
  JAVA_VERSION: 17
  JAVA_DIST: corretto
  # DOCKER env
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/backend
  # HELM env
  HELM_DIRECTORY: helm
  HELM_RELEASE_NAME: simonsays
  # K8S env
  K8S_API: https://pm4.init-lab.ch/k8s/clusters/local
  K8S_NAMESPACE: simonsays-stage


jobs:
  gradle-build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout sources
        uses: actions/checkout@v4
      - name: gradle-build
        uses: ./.github/actions/gradle-build
        with:
          working-directory: ${{ env.BACKEND_DIRECTORY }}
      - name: sonarcloud scan backend
        uses: SonarSource/sonarcloud-github-action@v2.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ${{ env.BACKEND_DIRECTORY }}