name: ci/cd backend pipeline

on:
  - push

env:
  # JAVA env
  JAVA_VERSION: 17
  JAVA_DIST: corretto
  GRADLE_VERSION: 8.5
  # DOCKER env
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/backend

defaults:
  run:
    working-directory: SimonSaysBackend

jobs:
  gradle-build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout sources
        uses: actions/checkout@v4
      - name: setup java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DIST }}
          cache: gradle
      - name: gradle setup
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
      - name: gradle build
        run: ./gradlew build
      - name: upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend
          # action ignores default working directory
          # see https://github.com/actions/upload-artifact/issues/294
          path: SimonSaysBackend/build/libs
          retention-days: 1
          if-no-files-found: error
  image-build:
    runs-on: ubuntu-22.04
    needs: [gradle-build]
    steps:
      - name: checkout sources
        uses: actions/checkout@v4
      - name: download artifacts
        uses: actions/download-artifact@v4
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3
      - name: docker login
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: extract metadata for docker image
        uses: docker/metadata-action@v5.5.1
        id: image-meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: latest
      - name: build and push docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}



