name: default backend pipeline running on each commit

on:
  - push
env:
  # GENERAL
  BACKEND_DIRECTORY: SimonSaysBackend
  # JAVA env
  JAVA_VERSION: 17
  JAVA_DIST: corretto
  GRADLE_VERSION: 8.5
  # DOCKER env
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/backend
  # HELM env
  HELM_DIRECTORY: helm
  HELM_RELEASE_NAME: simonsays-backend
  # K8S env
  K8S_API: https://pm4.init-lab.ch/k8s/clusters/local
  K8S_NAMESPACE: simonsays-stage


jobs:
  gradle-build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout sources
        uses: actions/checkout@v4
      - name: gradle-build
        uses: ./.github/actions/gradle-build
        with:
          working-directory: ${{ env.BACKEND_DIRECTORY }}
  image-build:
    runs-on: ubuntu-22.04
    needs: [gradle-build]
    steps:
      - name: checkout sources
        uses: actions/checkout@v4
      - name: image-build
        uses: ./.github/actions/image-build
        with:
          working-directory: ${{ env.BACKEND_DIRECTORY }}
          registry: ${{ env.REGISTRY }}
          image-name: ${{ env.IMAGE_NAME }}
          tags: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}

  test-helm-chart:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout sources
        uses: actions/checkout@v4
      - name: test helm
        uses: ./.github/actions/helm-test
        with:
          helm-directory: ${{ env.HELM_DIRECTORY }}

  deploy-helm-ci:
    runs-on: ubuntu-22.04
    needs: [image-build]
    environment: staging
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout sources
        uses: actions/checkout@v4
      - name: deploy
        uses: ./.github/actions/helm-release
        with:
          helm-directory: ${{ env.HELM_DIRECTORY }}
          k8s-token: ${{ secrets.K8S_TOKEN }}
          k8s-api: ${{ env.K8S_API }}
          k8s-namespace: ${{ env.K8S_NAMESPACE }}
          helm-release-name: ${{ env.HELM_RELEASE_NAME }}
          helm-values-file: values-stage.yaml



