name: ci/cd backend pipeline

on:
  - push

env:
  JAVA_VERSION: 17
  GRADLE_VERSION: 8.5

jobs:
  gradle-build:
    defaults:
      run:
        working-directory: SimonSaysBackend
    runs-on: ubuntu-22.04
    steps:
      - name: checkout sources
        uses: actions/checkout@v4
      - name: setup java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: gradle setup
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
      - name: gradle build
        run: ./gradlew build