name: build application on tag

on:
  push:
    tags:
      - 'v*'

env:
  # GENERAL
  BACKEND_DIRECTORY: backend
  FRONTEND_DIRECTORY: frontend
  # JAVA env
  JAVA_VERSION: 17
  JAVA_DIST: corretto
  # NPM env
  NODE_VERSION: 20
  # DOCKER env
  REGISTRY: ghcr.io
  # HELM env
  HELM_DIRECTORY: helm
  HELM_RELEASE_NAME: simonsays
  # K8S env
  K8S_API: https://pm4.init-lab.ch/k8s/clusters/local
  K8S_NAMESPACE: simonsays-prod

jobs:
  backend:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout sources
        uses: actions/checkout@v4
      - name: gradle-build
        uses: ./.github/actions/gradle-build
        with:
          working-directory: ${{ env.BACKEND_DIRECTORY }}
      - name: image-build
        uses: ./.github/actions/image-build
        with:
          working-directory: ${{ env.BACKEND_DIRECTORY }}
          registry: ${{ env.REGISTRY }}
          image-name: ${{ github.repository }}/backend
          tags: ${{ github.ref_name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
  frontend:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout sources
        uses: actions/checkout@v4
      - name: npm-build
        uses: ./.github/actions/npm-build
        with:
          working-directory: ${{ env.FRONTEND_DIRECTORY }}
          node-version: ${{ env.NODE_VERSION }}
          api-url: https://simonsays-backend.pm4.init-lab.ch
      - name: image-build
        uses: ./.github/actions/image-build
        with:
          working-directory: ${{ env.FRONTEND_DIRECTORY }}
          registry: ${{ env.REGISTRY }}
          image-name: ${{ github.repository }}/frontend
          tags: ${{ github.ref_name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
  # TODO: add printer server build