name: frontend running on each commit

on:
  - push
env:
  # GENERAL
  FRONTEND_DIRECTORY: frontend
  # NPM env
  NODE_VERSION: 20
  # DOCKER env
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/frontend
  # HELM env
  HELM_DIRECTORY: helm
  HELM_RELEASE_NAME: simonsays
  # K8S env
  K8S_API: https://pm4.init-lab.ch/k8s/clusters/local
  K8S_NAMESPACE: simonsays-stage


jobs:
  frontend-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout sources
        uses: actions/checkout@v4
      - name: frontend-test
        uses: ./.github/actions/frontend-tests
        with:
          working-directory: ${{ env.FRONTEND_DIRECTORY }}
          backend-working-directory: ${{ env.BACKEND_DIRECTORY }}
          node-version: ${{ env.NODE_VERSION }}