name: frontend running on pull requests

on:
    pull_request:
    push:
        branches:
        - main
env:
  # GENERAL
  FRONTEND_DIRECTORY: frontend
  BACKEND_DIRECTORY: backend
  # NPM env
  NODE_VERSION: 20
  # DOCKER env
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/frontend
  # HELM env
  HELM_DIRECTORY: helm
  HELM_RELEASE_NAME: simonsays
  # K8S env
  K8S_API: https://pm4.init-lab.ch/k8s/clusters/local
  K8S_NAMESPACE: simonsays-stage
  JAVA_VERSION: 17
  JAVA_DIST: corretto

jobs:
  frontend-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout sources
        uses: actions/checkout@v4
      - name: frontend-test
        uses: ./.github/actions/frontend-tests
        with:
          working-directory: ${{ env.FRONTEND_DIRECTORY }}
          backend-working-directory: ${{ env.BACKEND_DIRECTORY }}
          node-version: ${{ env.NODE_VERSION }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}