name: frontend running on each commit

on:
  push:
    branches-ignore:
      - main
env:
  # GENERAL
  FRONTEND_DIRECTORY: frontend
  BACKEND_DIRECTORY: backend
  # NPM env
  NODE_VERSION: 20
  # DOCKER env
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/frontend
  # HELM env
  HELM_DIRECTORY: helm
  HELM_RELEASE_NAME: simonsays
  # K8S env
  K8S_API: https://pm4.init-lab.ch/k8s/clusters/local
  K8S_NAMESPACE: simonsays-stage
  JAVA_VERSION: 17
  JAVA_DIST: corretto

jobs:
  npm-build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout sources
        uses: actions/checkout@v4
      - name: npm-build
        uses: ./.github/actions/npm-build
        with:
          working-directory: ${{ env.FRONTEND_DIRECTORY }}
          node-version: ${{ env.NODE_VERSION }}
          api-url: http://localhost:8080