name: frontend running on each commit

on:
  - push
env:
  # GENERAL
  FRONTEND_DIRECTORY: frontend
  # NPM env
  NODE_VERSION: 20
  # DOCKER env
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/frontend
  # HELM env
  HELM_DIRECTORY: helm
  HELM_RELEASE_NAME: simonsays
  # K8S env
  K8S_API: https://pm4.init-lab.ch/k8s/clusters/local
  K8S_NAMESPACE: simonsays-stage


jobs:
  npm-build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout sources
        uses: actions/checkout@v4
      - name: npm-build
        uses: ./.github/actions/npm-build
        with:
          working-directory: ${{ env.FRONTEND_DIRECTORY }}
          node-version: ${{ env.NODE_VERSION }}
      - name: image-build
        uses: ./.github/actions/image-build
        with:
          working-directory: ${{ env.FRONTEND_DIRECTORY }}
          registry: ${{ env.REGISTRY }}
          image-name: ${{ env.IMAGE_NAME }}
          tags: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
  deploy-helm-ci:
    runs-on: ubuntu-22.04
    needs: [image-build]
    environment: staging
    steps:
      - name: checkout sources
        uses: actions/checkout@v4
      - name: deploy
        uses: ./.github/actions/helm-release
        with:
          helm-directory: ${{ env.HELM_DIRECTORY }}
          k8s-token: ${{ secrets.K8S_TOKEN }}
          k8s-api: ${{ env.K8S_API }}
          k8s-namespace: ${{ env.K8S_NAMESPACE }}
          helm-release-name: ${{ env.HELM_RELEASE_NAME }}
          helm-values-file: values-stage.yaml