name: printer running on main

on:
  push:
    branches:
      - main
env:
  # GENERAL
  PRINTER_DIRECTORY: printer
  # DOCKER env
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/printer-server
  # HELM env
  HELM_DIRECTORY: helm
  HELM_RELEASE_NAME: simonsays
  # K8S env
  K8S_API: https://pm4.init-lab.ch/k8s/clusters/local
  K8S_NAMESPACE: simonsays-stage


jobs:
  image-build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout sources
        uses: actions/checkout@v4
      - name: image-build
        uses: ./.github/actions/image-build
        with:
          working-directory: ${{ env.PRINTER_DIRECTORY }}
          registry: ${{ env.REGISTRY }}
          image-name: ${{ env.IMAGE_NAME }}
          tags: ${{ github.ref_name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          platforms: linux/arm64