name: security scan on pull requests
on:
  pull_request

jobs:
  semgrep-diff:
    runs-on: ubuntu-22.04
    container:
      image: semgrep/semgrep
    steps:
      - name: clone application source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: semgrep login
        run: |
          SEMGREP_APP_TOKEN=${{ secrets.SEMGREP_TOKEN }} semgrep login
      - name: differential sempgrep scan
        run: |
          semgrep scan \
            --error \
            --baseline-commit HEAD~